unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s
set -g mouse on

#Splits
bind v split-window -h
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n C-] next-window
bind -n C-[ previous-window
bind t new-window -c "#{pane_current_path}"
bind -n C-Enter resize-pane -Z

set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible

# Visuals
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @tmux-dotbar-position top
set -g @tmux-dotbar-justify "left"
set -g @tmux-dotbar-window-status-format " #W[#I] "
set -g @tmux-dotbar-status-left "#S"

run '~/.tmux/plugins/tpm/tpm'
