export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="eastwood"

plugins=(git)

source $ZSH/oh-my-zsh.sh

export PATH="/opt/homebrew/bin:$PATH"

alias vim=nvim

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

function find_project() {
    selected=$(find ~/Projects/ -type d -mindepth 1 -maxdepth 1 2>/dev/null | fzf -i) && zle -I
    if [[ -n $selected ]]; then
        cd $selected
    else
        cd $PWD
    fi
}

zle -N find_project
bindkey '^f' find_project

